version: '3'
services:
  api-nginx:
    image: nginx:latest
    restart: always
    container_name: api-nginx
    volumes:
      - ./images/nginx:/etc/nginx/conf.d
      - ../api:/var/www/app
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - api-php
      - price-notifier-postgres
    ports:
      - "83:80"
    networks:
      - price_notifier

  api-php:
    build: ./images/php
    restart: always
    container_name: api-php
    environment:
      APP_DEBUG: 1
    depends_on:
      - price-notifier-postgres
    volumes:
      - ../api:/var/www/app
      - ./images/php/custom_php.ini:/usr/local/etc/php/conf.d/custom_php.ini
    networks:
      - price_notifier

  price-notifier-postgres:
    image: postgres:12.2-alpine
    container_name: price-notifier-postgres
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: HCK6LrwUsVu64ZdF
      POSTGRES_DB: price_monitoring
    expose:
      - "5435"
    ports:
      - "5435:5435" # HOST:CONTAINER
    command: -p 5435
    restart: always
    networks:
      - price_notifier

  tg-service:
    build:
      context: ../
      dockerfile: ./services/tg-service/docker/Dockerfile
    container_name: tg-service
    restart: always
    volumes:
      - ./logs/tg-service:/opt/app/logs
    ports:
      - "5243:5243"
    networks:
      - price_notifier

  price-notifier-adminer:
    container_name: price-notifier-adminer
    image: adminer
    ports:
      - "8338:8080"
    restart: always
    networks:
      - price_notifier

networks:
  price_notifier: